[package]
name = "saikuru"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
warp = "0.3.7"
tokio = { version = "1.40.0", features = ["full"]}
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"